# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/radon_kria_acc/radon_kria_acc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc || ORIG_REF_NAME==radon_kria_acc} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==radon_kria_acc_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_xbar_0/radon_kria_acc_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_xbar_0 || ORIG_REF_NAME==radon_kria_acc_xbar_0} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_axi_interconnect_0_0/radon_kria_acc_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_axi_interconnect_0_0 || ORIG_REF_NAME==radon_kria_acc_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_radon_kria_ip_0_2/radon_kria_acc_radon_kria_ip_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_radon_kria_ip_0_2 || ORIG_REF_NAME==radon_kria_acc_radon_kria_ip_0_2} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_rst_ps8_0_99M_2/radon_kria_acc_rst_ps8_0_99M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_rst_ps8_0_99M_2 || ORIG_REF_NAME==radon_kria_acc_rst_ps8_0_99M_2} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_auto_ds_0/radon_kria_acc_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_auto_ds_0 || ORIG_REF_NAME==radon_kria_acc_auto_ds_0} -quiet] -quiet

# IP: bd/radon_kria_acc/ip/radon_kria_acc_auto_pc_0/radon_kria_acc_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radon_kria_acc_auto_pc_0 || ORIG_REF_NAME==radon_kria_acc_auto_pc_0} -quiet] -quiet

# XDC: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.gen/sources_1/bd/radon_kria_acc/radon_kria_acc_ooc.xdc
