# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.srcs/sources_1/bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2.xci
# IP: The module: 'radon_kria_acc_zynq_ultra_ps_e_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.gen/sources_1/bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'radon_kria_acc_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.gen/sources_1/bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'radon_kria_acc_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.srcs/sources_1/bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2.xci
# IP: The module: 'radon_kria_acc_zynq_ultra_ps_e_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.gen/sources_1/bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'radon_kria_acc_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/StudiaNoSync/SDUP/RadonTransformREPO/RadonKRIA/RadonKRIA.gen/sources_1/bd/radon_kria_acc/ip/radon_kria_acc_zynq_ultra_ps_e_0_2/radon_kria_acc_zynq_ultra_ps_e_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'radon_kria_acc_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
